export const ingredientMock = {
  meal: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: '.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53060',
      strMeal: 'Burek',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strInstructions: '',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
      strTags: 'Streetfood, Onthego',
      strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
      strIngredient1: 'Filo Pastry',
      strIngredient2: 'Minced Beef',
      strIngredient3: 'Onion',
      strIngredient4: 'Oil',
      strIngredient5: 'Salt',
      strIngredient6: 'Pepper',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: '.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      strTags: 'SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Butter',
      strIngredient3: 'Cheese',
      strIngredient4: 'Onion',
      strIngredient5: 'Red Pepper',
      strIngredient6: 'Red Chile Flakes',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 large',
      strMeasure2: '2 tbs',
      strMeasure3: '150g',
      strMeasure4: '1 large',
      strMeasure5: '1 large',
      strMeasure6: 'Pinch',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: 'oak the beans i',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
      strIngredient1: 'Broad Beans',
      strIngredient2: 'Spring Onions',
      strIngredient3: 'Garlic Clove',
      strIngredient4: 'Parsley',
      strIngredient5: 'Cumin',
      strIngredient6: 'Baking Powder',
      strIngredient7: 'Cayenne Pepper',
      strIngredient8: 'Flour',

      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52785',
      strMeal: 'Dal fry',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Indian',
      strInstructions: 'Wof wa.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
      strTags: 'Curry,Vegetarian,Cake',
      strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
      strIngredient1: 'Toor dal',
      strIngredient2: 'Water',
      strIngredient3: 'Salt',
      strIngredient4: 'Turmeric',
      strIngredient5: 'Ghee',
      strIngredient6: 'Chopped tomatoes',
      strIngredient7: 'Cumin seeds',
      strIngredient8: 'Mustard Seeds',
      strIngredient9: 'Bay Leaf',
      strIngredient10: 'Green Chili',
      strIngredient11: 'Ginger',
      strIngredient12: 'Cilantro',
      strIngredient13: 'Red Pepper',
      strIngredient14: 'Salt',
      strIngredient15: 'Sugar',
      strIngredient16: 'Garam Masala',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup',
      strMeasure2: '2-1/2 cups',
      strMeasure3: '1 tsp',
      strMeasure4: '1/4 tsp',
      strMeasure5: '3 tbs',
      strMeasure6: '1 cup',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '2',
      strMeasure10: '1 tbs chopped',
      strMeasure11: '2 tsp shredded',
      strMeasure12: '2 tbs ',
      strMeasure13: '1/2 tsp',
      strMeasure14: '1/2 tsp',
      strMeasure15: '1 tsp',
      strMeasure16: '1/4 tsp',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.instagram.com/p/BO21bpYD3Fu',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: '',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',

      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const lintKiler = () => {};
