export const ingredientMock = {
  meals: [
    {
      strMeal: 'Chick-Fil-A Sandwich',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',
      idMeal: '53016',
    },
    {
      strMeal: 'Chicken Couscous',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg',
      idMeal: '52850',
    },
    {
      strMeal: 'Chicken Fajita Mac and Cheese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg',
      idMeal: '52818',
    },
    {
      strMeal: 'Chicken Ham and Leek Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg',
      idMeal: '52875',
    },
    {
      strMeal: 'Chicken Quinoa Greek Salad',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg',
      idMeal: '53011',
    },
    {
      strMeal: 'General Tso\'s Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444113.jpg',
      idMeal: '52951',
    },
    {
      strMeal: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg',
      idMeal: '52993',
    },
    {
      strMeal: 'Katsu Chicken curry',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
      idMeal: '52820',
    },
    {
      strMeal: 'Rappie Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg',
      idMeal: '52933',
    },
  ],
};

export const nameMock = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: '',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
